[package]
name = "armc"
version = "1.0.0"
edition = "2021"
repository = "https://github.com/patrickfp93/armc/"
description = "A short description of my package"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
