[package]
name = "armc"
version = "1.4.5"
edition = "2021"
repository = "https://github.com/patrickfp93/armc/"
description = "Armc is a rust implementation that facilitates Mutex access to variables."
license = "MIT"


[dependencies]
paste = "1.0.12"
